### ISSUE TITLE
nonexistent directory

### ISSUE THREAD

**Issue by thetechgeekster** [don-teka/DNTK#1]
Hi and a Happy New Year. I just tried to install the ad-blocker to my padavan installation in my Mi Router 3 but this error appeared when running the shell file:
```
/opt # /etc/storage/adblock_update.sh
rm: can't remove '/opt/tmp/block.hosts': No such file or directory
touch: /opt/tmp/block.hosts: No such file or directory
/etc/storage/adblock_update.sh: line 22: can't create /opt/tmp/block.build.list: nonexistent directory
/etc/storage/adblock_update.sh: line 25: can't create /opt/tmp/block.build.list: nonexistent directory
/etc/storage/adblock_update.sh: line 28: can't create /opt/tmp/block.build.list: nonexistent directory
wget: server returned error: HTTP/1.1 503 Service Temporarily Unavailable
/etc/storage/adblock_update.sh: line 31: can't create /opt/tmp/block.build.list: nonexistent directory
/etc/storage/adblock_update.sh: line 46: can't create /opt/tmp/block.build.list: nonexistent directory
/etc/storage/adblock_update.sh: line 94: can't create /opt/tmp/block.build.list: nonexistent directory
/etc/storage/adblock_update.sh: line 103: can't create /opt/tmp/block.build.list: nonexistent directory
/etc/storage/adblock_update.sh: line 112: can't create /opt/tmp/block.build.before: nonexistent directory
awk: /opt/tmp/block.build.list: No such file or directory
/etc/storage/adblock_update.sh: line 122: can't create /opt/tmp/block.hosts: nonexistent directory
/opt # 
```
When I'm trying to make the /opt/tmp directory I get this message 
```
mkdir: can't create directory 'tmp': Read-only file system
```
Do you know what could be wrong? Thnak you!

**Comment by don-teka** [comment]
Are you using external hd or pendrive on your router? is entware enabled? the script is designed to work with external hd or pendrive on USB, if using internal memory there are some lines that need to be changed. The /opt/tmp folder is created when you enable entware, but you need an external HD or pendrive to work.

**Comment by thetechgeekster** [comment]
Oh, I see. I was not using an USB Drive for that. I'll try with a small USB Drive. Maybe you could update the README to include the requirement of the USB Drive.

Thank you!

**Comment by don-teka** [comment]
Thanks for the tip. when I wrote the README I assumed that everyone would be using some external storage on the router. I will update the readme.
